sudo: false
language: php
php:
  - 7.0
  - 7.1
before_script:
  - composer self-update
  - yes '' | pecl install -f mongodb-1.1
  - composer install
script:
  - ./vendor/bin/phpcs --standard=./vendor/chadicus/coding-standard/Chadicus src
